[package]
name = "atlas"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tokio = { version = "1.49.0", features = ["full"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }
serde = { version = "1.0.228", features = ["derive"] }
ulid = "1.2.1"
tower-http = { version = "0.6.8", features = ["trace"] }
rand = "0.10.0"
sha2 = "0.10.9"
memmap2 = "0.9.10"
bytemuck = "1.25.0"
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }

[dev-dependencies]
axum-test = "19.1.1"
tower-http = "0.6.8"
