name: Semver check

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
    branches:
      - develop

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major"